---
apiVersion: v1
kind: Pod
metadata:
  name: avp-test-pod
  namespace: default
spec:
  containers:
    - name: tester
      image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            date
            echo "Vault MESSAGE = $MESSAGE"
            echo "------------------------"
            sleep 5
          done
      env:
        - name: MESSAGE
          valueFrom:
            secretKeyRef:
              name: avp-test-secret
              key: MESSAGE
  restartPolicy: Always
